name: Deploy S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Create .env file
        run: |
          echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" > .env
          echo "REACT_APP_CLOUDFRONT_URL=${{ secrets.REACT_APP_CLOUDFRONT_URL }}" > .env

      - name: Install Dependencies
        run: npm ci --only=production

      - name: Build
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://dylan-web-app-bucket --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
